# Generated by Django 5.2.8 on 2026-01-16 10:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_company_contact_task_assigned_to_task_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '★ Poor'), (2, '★★ Fair'), (3, '★★★ Good'), (4, '★★★★ Very Good'), (5, '★★★★★ Excellent')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tasks.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Rating',
                'verbose_name_plural': 'Contact Ratings',
                'ordering': ['-created_at'],
                'unique_together': {('contact', 'user')},
            },
        ),
    ]
